backend:
  name: git-gateway
  # name: test-repo
  branch: main

media_folder: "netlify/functions/server/content/images/uploads"

collections:
  - name: "event"
    label: "Forside begivenhed"
    folder: "netlify/functions/server/content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Afholdelsesdato",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - { label: "Billed", name: "thumbnail", widget: "image", required: false }
      - { label: "Tekst", name: "body", widget: "markdown" }
