backend:
  name: git-gateway
  # name: test-repo
  branch: main

media_folder: "images/uploads"

collections:
  - name: "event"
    label: "Forside begivenhed"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Dato", name: "date", widget: "datetime" }
      - { label: "Billed", name: "thumbnail", widget: "image", required: false }
      - { label: "Tekst", name: "body", widget: "markdown" }
      - { label: "Tekst", name: "body", widget: "markdown" }
