backend:
  name: git-gateway
  # name: test-repo
  branch: main

media_folder: "public/images/uploads"

collections:
  - name: "event"
    label: "Forside begivenhed"
    folder: "netlify/functions/server/content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Billed", name: "thumbnail", widget: "image", required: false }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: "about-constituency"
    label: "Om valgmenigheden"
    create: true
    folder: "netlify/functions/server/content/about-constituency"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: "alter"
    label: "Alter billedet"
    folder: "netlify/functions/server/content/alter"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: "priest-blog"
    label: "Præsten har ordet"
    create: true
    folder: "netlify/functions/server/content/priest-blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: "signup"
    label: "Bliv medlem"
    folder: "netlify/functions/server/content/signup"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: "contact"
    label: "Kontakt"
    folder: "netlify/functions/server/content/contact"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: "church-paper"
    label: "Kirkeblad"
    create: true
    folder: "netlify/functions/server/content/church-paper"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Fil", name: "file", widget: "file" }
